### ISSUE TITLE
SpinKitPouringHourglass name changed

### ISSUE THREAD

**Issue by idemirel** [nslog11/flutter_easyloading#120]
**Describe the bug**
Try correcting the name to the name of an existing method, or defining a method named 'SpinKitPouringHourglass'.
        _indicator = SpinKitPouringHourglass(
                     ^^^^^^^^^^^^^^^^^^^^^^^
                                                                        

FAILURE: Build failed with an exception.

The dependent flutter_spinkit package upgraded and the Class name **SpinKitPouringHourglass** changed to **SpinKitPouringHourGlass** , thus build error occures

The related link is [here](https://github.com/jogboms/flutter_spinkit/releases/tag/v5.1.0)

**Comment by kidozh** [comment]
I also encounter this problem. After I fix the typo at line 166 of `\lib\src\widgets\indicator.dart`, problem solved.

**Comment by MrFantuk** [comment]
> I also encounter this problem. After I fix the typo at line 166 of `\lib\src\widgets\indicator.dart`, problem solved.

could u provide more information?

my problem, quite simile:

Error: Method not found: 'LoadingIndicator'.
    Widget w = indicator ?? (_instance.indicatorWidget ?? LoadingIndicator());
                                                          ^^^^^^^^^^^^^^^^

**Comment by kidozh** [comment]
> > I also encounter this problem. After I fix the typo at line 166 of `\lib\src\widgets\indicator.dart`, problem solved.
> 
> could u provide more information?
> 
> my problem, quite simile:
> 
> Error: Method not found: 'LoadingIndicator'.
> Widget w = indicator ?? (_instance.indicatorWidget ?? LoadingIndicator());
> ^^^^^^^^^^^^^^^^

Your problem seems different from mine.  My easyloading version is 5.0.0, have you tried to upgrade your version to the latest one?

**Comment by MrFantuk** [comment]
> 5.0.0, ??

I have 3.0.0
I replace my \lib\src\widgets\indicator.dart with GitHub package repo, make changes in 'SpinKitPouringHourGlass' and it works.

**Comment by kidozh** [comment]
> > 5.0.0, ??
> 
> I have 3.0.0
> I replace my \lib\src\widgets\indicator.dart with GitHub package repo, make changes in 'SpinKitPouringHourGlass' and it works.

Perhaps upgrading your dependency in your project should be a better choice. A small suggestion.

**Comment by ashutosh-mulik** [comment]
Just upgraded dependencies and now I'm getting this error.

Try correcting the name to the name of an existing method, or defining a method named 'SpinKitPouringHourglass'.
        _indicator = SpinKitPouringHourglass(
                     ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by MrFantuk** [comment]
> > > 5.0.0, ??
> > 
> > 
> > I have 3.0.0
> > I replace my \lib\src\widgets\indicator.dart with GitHub package repo, make changes in 'SpinKitPouringHourGlass' and it works.
> 
> Perhaps upgrading your dependency in your project should be a better choice. A small suggestion.

as I see, last version is 3.0.0
I didn't find any newer version.



> Just upgraded dependencies and now I'm getting this error.
> 
> Try correcting the name to the name of an existing method, or defining a method named 'SpinKitPouringHourglass'.
> _indicator = SpinKitPouringHourglass(
> ^^^^^^^^^^^^^^^^^^^^^^^

as kidozh method:
manually change SpinKitPouringHourglass to SpinKitPouringHourGlass

**Comment by ashutosh-mulik** [comment]
Worked Thanks 👍👍

**Comment by kaelli** [comment]
the bug reason is flutter_spinkit update to 5.1.0 and change the SpinKitPouringHourglass to SpinKitPouringHourGlass,but this lib use SpinKitPouringHourglass, so，add  flutter_spinkit: 5.0.0 in the dependencies ,then will well

**Comment by taepunphu** [comment]
> > > > 5.0.0, ??
> > > 
> > > 
> > > I have 3.0.0
> > > I replace my \lib\src\widgets\indicator.dart with GitHub package repo, make changes in 'SpinKitPouringHourGlass' and it works.
> > 
> > 
> > Perhaps upgrading your dependency in your project should be a better choice. A small suggestion.
> 
> as I see, last version is 3.0.0
> I didn't find any newer version.
> 
> > Just upgraded dependencies and now I'm getting this error.
> > Try correcting the name to the name of an existing method, or defining a method named 'SpinKitPouringHourglass'.
> > _indicator = SpinKitPouringHourglass(
> > ^^^^^^^^^^^^^^^^^^^^^^^
> 
> as kidozh method:
> manually change SpinKitPouringHourglass to SpinKitPouringHourGlass

thank you guy, that work for me
