### ISSUE TITLE
The method 'SpinKitPouringHourglass' isn't defined for the class '_LoadingIndicatorState'.

### ISSUE THREAD

**Issue by HouHouSir** [nslog11/flutter_easyloading#123]
Error: The method 'SpinKitPouringHourglass' isn't defined for the class '_LoadingIndicatorState'.
 - '_LoadingIndicatorState' is from 'package:flutter_easyloading/src/widgets/indicator.dart' ('../../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.0/lib/src/widgets/indicator.dart').
Try correcting the name to the name of an existing method, or defining a method named 'SpinKitPouringHourglass'.
        _indicator = SpinKitPouringHourglass(

**Comment by zakblacki** [comment]
Same problem !

**Comment by sinzz** [comment]
Same problem !flutter_spinkit changed the SpinKitPouringHourglass  name in 5.1.0

**Comment by nslog11** [comment]
please update to v3.0.1
#120
