### ISSUE TITLE
Error: A value of type 'Object?' can't be returned from a function with return type 'List<BoxShadow>?'.

### ISSUE THREAD

**Issue by hczmail** [nslog11/flutter_easyloading#126]
/D:/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_easyloading-3.0.2/lib/src/theme.dart:59:11: Error: A value of type 'Object?' can't be returned from a function with return type 'List<BoxShadow>?'.
 - 'Object' is from 'dart:core'.
 - 'List' is from 'dart:core'.
 - 'BoxShadow' is from 'package:flutter/src/painting/box_shadow.dart' ('/D:/flutter/packages/flutter/lib/src/painting/box_shadow.dart').
          ? EasyLoading.instance.boxShadow ?? BoxShadow()
          ^

FAILURE: Build failed with an exception.

**Comment by nslog11** [comment]
please update to v3.0.3

**Comment by sondt2709** [comment]
v3.0.3 has an issue related to [backgroundColor](https://github.com/nslog11/flutter_easyloading/issues/128), you can keep current version and add this line
```
EasyLoading.instance..boxShadow = const []
```
It should work
